### ISSUE TITLE
logger examples?

### ISSUE THREAD

**Issue by davispolito** [ElandaSunshine/Jaut#7]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see an example of how to use the logger

**Comment by ElandaOfficial** [comment]
Heya there!
Yes, the logging documentation is still not up yet, I am currently on documenting everything but with JAUT I have slacked off a little lately.

For now, however, let me introduce you really quickly how you can use the logger:
Here's a simple logging implementation:
```c++
#include <jaut_logger/jaut_logger.h>

// if you need a non-async logger, then jaut::LoggerSimple will do the job otherwise jaut::LoggerAsync
// this just determines whether the logging should happen on the same or a dedicated logging thread

// you can change some setting per logger here, like when to flush, default log level ect.
jaut::LoggerSimple::Options options;
options.logLevel = jaut::LogLevel::Info;

// for the sink, which purpose is to handle incoming messages, we use "jaut::LogSinkCout" as an example,
// which will log to cout
// as constructor argument it takes a formatter, let's keep with the default one
auto sink = std::make_unique<jaut::LogSinkCout>();

// third parameter you can pass the logger sinks that it uses to output your message
jaut::LoggerSimple logger("logger name", options, std::move(sink));

// and then you can log messages
logger.info("Hello, this is my first log message");

// or if you prefer streaming syntax
logger << jaut::LogLevel::Info << "Hello, this is my first message";
```

I absolutely understand that it is very unintuitive if there is no documentation, but you can always join the discord (if you want) and you will get a much better explanation there: https://discord.com/invite/jzRyAtnJBc

Have fun :)

**Comment by ElandaOfficial** [comment]
Further discussion should be outsourced to Discord!
